mkdir Introduction
mkdir ExceptionsAndExceptionHandling
mkdir Interfaces
mkdir Generics
mkdir AnonymousMethods
mkdir Predicates
mkdir Collections
mkdir Enumerators
mkdir IEnumerable
mkdir RunTimeTypingInformation
mkdir CustomAttributes
mkdir TVirtualInterfaces
mkdir WritingTestableCode
mkdir DependencyInjectionConstructorInjection
mkdir DependencyInjectionServiceLocatorAndTheDelphiSpringFramework
mkdir UnitTesting
mkdir FakingAndIsolationFrameworks
mkdir Conclusion
:: mkdir AppendixA:SettingupTheDelphiSpringFramework
:: mkdir AppendixB:Nick’sDelphiStory
:: mkdir AppendixC:UsefulDelphiResources
